### ISSUE TITLE
Use README as first item in the list of FileSets.

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#1012]
If the user includes a README.* move that to the first position in the file list.

**Comment by carolyncole** [comment]
Only for certain resource Types:  @olendorf will provide the list

**Comment by olendorf** [comment]
I put things that weren't so much text and could be sort of complicated and hard to understand just by looking at it. Also looking through the repo there were some audio and cartographic that were really data like. So images make sense to have readmes for instance because a micrscopic image might need a fair amount of explanation. 

Audio
Dataset
Image
Map/Cartographic
Software/Code
Video 
Other

**Comment by awead** [comment]
@olendorf In looking further into this, there's two ways we can do this:
1. Just display it at the top (easy)
2. Re-order the file sets (hard)

The problem with the easy route is that users can specify their own order via the file manager, so just displaying it with a readme at the top would look misleading by not displaying what the user had explicitly set.

The hard route is hard because there are several different places where file sets get added. We'd need to come up with a mechanism for tracking all the file sets added to a work, then update the order after they were all added. Additionally, the file manager will need to be modified so that readme file sets can't have their order changed.

Given that the readme will be displayed at the top of the work page, is it still necessary to display the file set at the top of the list? If so, do you have opinions on the two options for display?

**Comment by rko5039** [comment]
@awead Given the difficulty I think the fact that we are displaying the contents makes this not so important.

**Comment by awead** [comment]
@olendorf Should we close the issue or refine it further?
