### ISSUE TITLE
URLs with "scholarsphere:"

### ISSUE THREAD

**Issue by hectorcorrea** [psu-libraries/scholarsphere-3#140]
Our logs shows several requests for URLs that include "scholarsphere:" which I understand we supported at one point (for example: /collections/scholarsphere:123) 

Currently scholarsphere throws a "System Error" when it receives these requests. 

We should update ScholarSphere to detect these cases in files, collections, and downloads (are there any others?) and redirect the user to the proper URL without "scholarsphere:" on it. For example HTTP GET /collections/scholarsphere:123 should return an HTTP status 301 (moved permanently) to /collections/123

Here is an example of a page referencing the old URLs: https://www.libraries.psu.edu/psul/socialsciences/docdigiproj/environmentalsci.html

**Comment by carolyncole** [comment]
We should use something similar to what we used to do: https://github.com/projecthydra/sufia/blob/5.0.0-stable/app/controllers/concerns/sufia/files_controller_behavior.rb#L41 and
https://github.com/projecthydra/sufia/blob/5.0.0-stable/app/controllers/concerns/sufia/controller.rb#L15-L17

Except we should remove the namespace.  

I marked this as high priority since we know of users that need this.

**Comment by carolyncole** [comment]
This fix has been put into production.
