### ISSUE TITLE
Generic File show page should use solr instead on Fedora

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#146]
The GenericFile show page should use solr for showing the document instead of using the fedora document.
Here is where we used to load from solr before F4
https://github.com/psu-stewardship/scholarsphere/blob/develop/app/controllers/generic_files_controller.rb#L22-L29

Here is the removed code:
https://github.com/psu-stewardship/scholarsphere/blob/v2.1.1/app/controllers/generic_files_controller.rb#L12-L15

Here is some code in sufia that may help: https://github.com/projecthydra/sufia/issues/711

**Comment by awead** [comment]
Substituting a solr-based GenericFile object as opposed to an ActiveFedora one raises a problem here:
https://github.com/projecthydra/sufia/blob/master/sufia-models/app/services/sufia/generic_file_audit_service.rb#L33
because the audit service needs access to the file's version information.

I believe the best way to fix this is to add version information to ActiveFedora::LoadableFromJson::SolrBackedMetadataFile so that Sufia's audit service can remain unchanged and you can get the same results from the audit service whether you use a full AF object or just one loaded from Solr.

**Comment by awead** [comment]
The other problem is characterization information. We'd need to override this view:
https://github.com/projecthydra/sufia/blob/master/app/views/generic_files/_show_details.html.erb#L20
and replace the call to .characterization_terms with something else.
