### ISSUE TITLE
My Files pagination issue

### ISSUE THREAD

**Issue by nty5001** [psu-libraries/scholarsphere-3#197]
When viewing a user's My Files page and navigating to any page view after the initial page, selecting different view options can cause all visible files to disappear. Links to other pages also disappear, leaving the user stuck until they refresh the page.

http://screencast.com/t/UFsXCJMztX

It is suspected that the behavior may also extend to My Collections, My Highlights, and Files Shared with Me sections. Would need more time to populate test samples.

**Comment by awead** [comment]
Having looked at this, here's what's happening:

You have 15 total items, 10 are displayed per page. If you navigate to the second page of results, you'll see results 11-15. When you change the number per page setting to 50, it refreshes the page but still retains the existing page2 parameter. So you're displaying the second page of results, but with 50 per page. Because you only have 15 total items, all of them are on page 1, so page 2 is empty.

The solution here would be to reset to page 1 if the number per page parameter is changed.

**Comment by carolyncole** [comment]
We are hacking CatalogController for the MyFiles so we should see what Blacklight is doing.
