### ISSUE TITLE
Add a  metadata field to GenericFile for  Share notify ID

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#204]
We need to add an additional field for the share notify id that gets returned when we send a file to share.

**Comment by carolyncole** [comment]
related to #188 & #201

**Comment by carolyncole** [comment]
This does not have to be a fedora field, it can be a database mapping between the id and the share id like the fact that an item is a trophy is stored separately from the file

**Comment by carolyncole** [comment]
@awead Here is where the zotero information is being stored: https://github.com/projecthydra/sufia/blob/master/sufia-models/app/models/concerns/sufia/generic_file/metadata.rb#L13
I am not saying we need to follow this pattern, but I dug it up so I am documenting it.

**Comment by awead** [comment]
@cam156 well, I know we're trying to get away from custom predicates in Sufia (see projecthydra/sufia#1327) but this isn't going into Sufia. However, I'm leery of custom predicates anyway. At the very least, they ought to be public predicates that are maintained in a more formal way. This doesn't seem like a good way to do RDF. I also question the preservation-ness of arkivo and now share-notify metadata. Perhaps it is more to have good RDF metadata than to be "preservation-y", but if we want to have good RDF, see above...

Maybe @mjgiarlo can fill us in on the back story.

I think we should go with what the library wants, since they're requesting the feature. ping @kestlund

**Comment by mjgiarlo** [comment]
Storing the Arkivo checksum as a property on the GF certainly wasn't done for good RDFness though maybe there's a preservation-y aspect. It's there just so we can tell 1) which files came over from Arkivo, and 2) whether the files were corrupted in transit from Arkivo (though we don't verify this in practice).

**Comment by awead** [comment]
@mjgiarlo yeah, that's the same criteria we need to have share notify ids stored as well, so maybe we just continue down that road. Although, a difference predicate might be better. Let's see if anyone weighs in.

**Comment by mjgiarlo** [comment]
@awead You might also want to ping Sufia folks over on that GitHub repo, or maybe even raise that on hydra-tech. The level of interest in SHARE Notify or where best to squirrel away identifier metadata could be greater than you think.

**Comment by kestlund** [comment]
@awead, I agree with @mjgiarlo  that the interest in SHARE Notify metadata may be broader. You might even get @wickr and @vantuyls to consider adding a predicate to opaquenamespace as they may want something similar.

**Comment by awead** [comment]
I've added a scholarsphere predicate for now, but this will change. After contacting the SHARE Notify devs, the forthcoming API will accept URIs from SS as their unique identifiers and update resources on the SHARE side if it already exists. This should make the need for keeping local metadata unnecessary.
