### ISSUE TITLE
File Uploaded many small files fails

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#453]
In ScholarSphere 3.0
When I create a new work
And I choose many (10 or more) small (15KB or less) files using add files or add folder
Then I get some blank lines where a file should be in the upload screen

**Comment by mtribone** [comment]
guessing jquery file uploader problem

**Comment by carolyncole** [comment]
The example of how to create #387

**Comment by carolyncole** [comment]
I am seeing this issue when I upload the files from the archivesphere/spec/fixtures directory

I am seeing it on both the current and the new QA systems

Current QA:
<img width="927" alt="screen shot 2017-04-11 at 11 48 55 am" src="https://cloud.githubusercontent.com/assets/1599081/24918009/df4ee1d2-1eac-11e7-85c4-432223881226.png">

New QA
<img width="946" alt="screen shot 2017-04-11 at 11 47 02 am" src="https://cloud.githubusercontent.com/assets/1599081/24918011/e07f17d4-1eac-11e7-87e0-1133b06159f5.png">

**Comment by awead** [comment]
@cam156 I'm not able to reproduce this. I tried uploading all the files in the fixtures directory to both QA systems and didn't see the blank lines. I know it's been a problem in the past. Could it be some kind of transient issue with the servers?

**Comment by awead** [comment]
@cam156 ok, I'm seeing it now, but with uploading some other small files I had used previously.

**Comment by awead** [comment]
@cam156 update: I think I've figured out the problem is on the client side.

All the requests are making it to the server, files and uploaded, and the server is responding with 200 and a json response that includes the id of the Sufia::Uploaded file. However, the web browser seems to be unable to "keep up" and inserts the blank lines for the first couple of server responses before it finally "catches up" and starts inserting the actual json responses from the server. If you look in the network log of the browser, you can see all the responses. It's just the browser that hasn't inserted the first couple into the DOM. Therefore, when you hit send on the form, it's not sending a complete list of file ids for work.

Furthermore, if I throttle the network connection in the browser to be slower, the problem goes away. So... the server is just responding too quickly?

**Comment by carolyncole** [comment]
@awead I wonder if it is just not thread safe.  Aka multiple responses at the same time cause the issue.  Throttling the connection would likely make the responses come back in sequence?  Not sure if that is true

**Comment by awead** [comment]
@cam156 good point. However, wouldn't we see the problems throughout the upload instead of just at the beginning? I also wonder if some responses come back from qa1 and the qa2, so you're getting responses from two points.
