### ISSUE TITLE
Picture in featured researchers is bad

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#46]
The styling on featured researchers is weird...
![screen shot 2015-01-19 at 10 19 23 am](https://cloud.githubusercontent.com/assets/1599081/5803123/67a03956-9fc9-11e4-9258-ae745f524c52.png)

**Comment by mtribone** [comment]
So my guess is that because the picture is floating left and there is very little content in that block the phrase cloud is moving up. The WYSIWYG isn't always super intuitive if you don't keep an eye on the options that you select (viewable in the bottom bar when the photo is selected) and make adjustments.
![screen shot 2015-01-19 at 1 02 24 pm](https://cloud.githubusercontent.com/assets/4163828/5805281/77f21a4c-9fdb-11e4-8aa8-04c54d3ab94d.png)

**Comment by jcoyne** [comment]
This is because the mime_type() method on GenericFile is different when the file is instantiated using find  vs load_instance_from_solr:

```ruby
f = GenericFile.find('ad2722b8-a1cf-41d3-8184-4e15e24335d7')
=> #<GenericFile id: "ad2722b8-a1cf-41d3-8184-4e15e24335d7", mime_type: "image/jpeg",  ...
g = GenericFile.load_instance_from_solr('ad2722b8-a1cf-41d3-8184-4e15e24335d7')
=> #<GenericFile id: "ad2722b8-a1cf-41d3-8184-4e15e24335d7", mime_type: "i", ...
f.mime_type
=> "image/jpeg"
g.mime_type
=> "i"
```

**Comment by mjgiarlo** [comment]
Well, that's odd.

**Comment by jcoyne** [comment]
The fix is in https://github.com/projecthydra/active_fedora/pull/694

**Comment by jcoyne** [comment]
Oops, I've been commenting on the wrong ticket. Moving these comments to #47
