### ISSUE TITLE
Write up Contact email for user testing participation

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#470]
How are we going to ask people to participate in user testing for ScholarSphere 3.0

**Comment by olendorf** [comment]
Hi everyone

I am writing you because you have recently deposited content into ScholarSphere or have expressed a desire to do so. We are constantly working on new features and updates.

In the coming months we are rolling out some big changes in how you can organize your data. We will be making it possible to organize multi-file objects such as datasets into a single group of files. As someone who has recently uploaded content, we are hoping you will be willing to serve as a tester for the new feature and help as ensure that it functions well for you and other users.

The testing should only take 30 minutes or less and we can do it any time in the next couple of months. To make it as easy for you as possible we will come to your office and provide you with test data for use. All you need to do is try out the interface and share your thoughts. 

If you are willing to participate just respond to this email and we will try to find a time that works for you.

Thank you very much.

Rob

**Comment by olendorf** [comment]
I went ahead and sent the email out so Ima gonna close this one.
