### ISSUE TITLE
Edit Work <head><title> Content can be Better

### ISSUE THREAD

**Issue by mtribone** [psu-libraries/scholarsphere-3#526]
"Web pages should include a TITLE tag within the HEAD area, and the title should be unique to each page on the Web site. The TITLE can be repeated as the H1 of the page."

http://accessibility.psu.edu/titleshtml/

We could do a little better job with the `<head><title>` and the work `<h1>` even though they both can be the same. Per the example on the accessibility site, we could give the `<head><title>` some context about its relationship in the site.

The `<head><title>` when editing a work shows both the work title and its work identifier.
"Star Wars Interfaces // Work [70r967436w] // ScholarSphere"

Perhaps a better example:
"Edit Work | Star Wars Interfaces | ScholarSphere"

**Comment by carolyncole** [comment]
Changed the work head title to do the following:
1. Use the bar separator instead of the double //
1. First node should include page action (show vs edit)
1. Second Node should be title
1. Third node should be "Work id: "id""
1. Forth Node should be scholarSphere

`Edit Work| Star Wars Interfaces| Word id: 70r967436w| ScholarSphere`
`Work| Star Wars Interfaces| Word id: 70r967436w| ScholarSphere`

Make the collection title constant with work.
