### ISSUE TITLE
Original files uploaded via Box do not have the correct name when downloaded

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere-3#532]
Given I have a single new work
With a file uploaded via Box, either in batch mode or not
When I download the file
Then the file should have the same and extension as the file that was uploaded

Currently, the file is downloaded as `rn870zr64v20170109-3424-16zikav` or other similar UID. The file content is correct, in that if I rename the file to its original extension, I'm able to open it.

**Comment by carolyncole** [comment]
The could be any file with browse everything.  The file name seems to be set to the url, instead of the original name.
The paramters used by the downloads controller are not getting set correctly: https://github.com/projecthydra/hydra-head/blob/master/hydra-core/app/controllers/concerns/hydra/controller/download_behavior.rb#L83
