### ISSUE TITLE
Data sets not uploading correctly

### ISSUE THREAD

**Issue by olendorf** [psu-libraries/scholarsphere-3#634]
https://scholarsphere.psu.edu/files/4j03cz77z

@cam156 Looks like the uploads failed silently. I'll contact the creator and get new copies.

**Comment by carolyncole** [comment]
@olendorf I think this is the same as an error we have seen before, https://servicedesk.css.psu.edu/browse/SCHSPHERE-1923?jql=project%20%3D%20SCHSPHERE%20AND%20text%20~%20%22csv%22.  The content is on the system, but can not be retrieved due to a jena parsing error.  I believe when we upgrade to the latest fedora this will be fixed

**Comment by carolyncole** [comment]
@olendorf I ran a test on the original file in the jira ticket. I was able to upload and download the CSV file on our QA system.

**Comment by olendorf** [comment]
@cam156  this can be closed?
