### ISSUE TITLE
Import failed with MiniMagick::Error

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#660]
arguments:
```
- _aj_globalid: gid://scholar-sphere/FileSet/6m900nt031
- "/opt/heracles/deploy/scholarsphere/releases/20170217172726/tmp/uploads/6m900nt031_version1_101101Nb_PV-NES-DsRedzstack_04.lsm"
locale: en
```

Exception
```
MiniMagick::Error
Error
`mogrify -flatten /dlt/scholarsphere/upload_qa/tmp/mini_magick20170220-1453-a1awlf.lsm` failed with error: mogrify: /dlt/scholarsphere/upload_qa/tmp/mini_magick20170220-1453-a1awlf.lsm: unknown field with tag 34412 (0x866c) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/715. mogrify: incorrect count for field "BitsPerSample" (3, expecting 2); tag trimmed. `/dlt/scholarsphere/upload_qa/tmp/mini_magick20170220-1453-a1awlf.lsm' @ warning/tiff.c/TIFFWarnings/715. mogrify: incorrect count for field "StripOffsets" (3, expecting 2); tag trimmed. `/dlt/scholarsphere/upload_qa/tmp/mini_magick20170220-1453-a1awlf.lsm' @ warning/tiff.c/TIFFWarnings/715. mogrify: incorrect count for field "StripByteCounts" (3, expecting 2); tag trimmed. `/dlt/scholarsphere/upload_qa/tmp/mini_magick20170220-1453-a1awlf.lsm' @ warning/tiff.c/TIFFWarnings/715. mogrify: Sorry, can not handle RGB image with Color channels=2. 

```

**Comment by carolyncole** [comment]
Need to replicate the error to determine why.  This ticket should create an additional ticket once we understand why.

**Comment by awead** [comment]
@cam156 I took the same file from QA and reuploaded it again and it worked:

https://scholarsphere-qa.dlt.psu.edu/concern/generic_works/c2f75r950s

Is there any way to confirm from @olendorf if this is the same file? I copied it from the tmp directory on QA.

**Comment by carolyncole** [comment]
@awead here is a link to the original file https://scholarsphere.psu.edu/files/x346dp78g

**Comment by awead** [comment]
@cam156 @olendorf 

The gist is, IM does not support converting this file. The issue is that the file has multiple files within it, different than a standard multipage tiff. I downloaded an app called Fiji that can view lsm files and this one has two "channels" each with its own Z-stack (this is apparently they're called) of 7 images. So it's like two multi-page files, each with 7 images, wrapped into one file. I don't know the specific reasons for this, but there it is.

IM will not convert multichannel tiffs because libtiff won't: http://www.wizards-toolkit.org/discourse-server/viewtopic.php?t=16843

Oddly enough, however, the mogrify command succeeds in creating an image. It could be the first image or channel of the file, but since it encounters an error, HydraDerivatives throws it. A potential solution could be to capture it and move on, reporting it to a log or message.

**Comment by awead** [comment]
Followup issue is #706
