### ISSUE TITLE
Current User Email

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#717]
Need to create wording draft to send on to Comms JILL SHOCKEY for review before sending.  Then need emails and decide when to send? 1 week out?

**Comment by olendorf** [comment]
Hello Scholarsphere User

We are pleased to announce the release of Scholarsphere 3.0. This new version of Scholarsphere will have a few exciting new features we think you appreciated. 

First, we will be introducing the "Work". Previously we had collections, which many of you used for multi-file projects. A work is similar to a collection in that it will handle multiple files, but it is designed for instances where the files are related to each other as a cohesive unit, for example, software or research data. This will also provide a framework to introduce new features that are specific to a work.

We will also be changing our privacy settings. We will no longer allow content to be private forever. However,  you can embargo content, so that it is private for up to two years, after which time it becomes public.

After considerable user testing we will also be improving or interface to make Scholarsphere easier to use. We have especially improved accessibility for sight challenged users.

The new version of Scholarsphere will be rolled out on **[insert date here]** and we will be down for **[insert time span here]** during which time you will not be able to access content or upload new content. We apologize for any inconvenience that might present, but we think you will like the new features we are adding.

**Comment by olendorf** [comment]
@cam156 @mtribone @awead 

Hey ya'll, have a look at this email and edit as needed. Once we have it finalized with dates and stuff we can send it to marketing.

**Comment by awead** [comment]
@olendorf looks great. Just a couple of corrections:
1 paragraph line 2: we think you +will+ appreciate
4p, l1: improving +our+ interface
4p, l2: "sight-challenged" or "visually impaired" (?) whichever is more current

**Comment by mtribone** [comment]
@awead Yeah if we look at the target audience from the accessibility site:

http://accessibility.psu.edu/accommodations/

I think we're tackling visual impairment, color blindness/deficiency, and impaired mobility with the work that we have done.

**Comment by carolyncole** [comment]
Need to get a list of current users and get ready to send this out. along with a final draft. The list of users is here: https://psu.box.com/s/xasw0juhkncgu29r53ikqmvdtbh45b0o

**Comment by carolyncole** [comment]
Hello Scholarsphere User

We are pleased to announce the release of Scholarsphere 3.0. This new version of Scholarsphere will have a few exciting new features we think you will appreciate.

First, we will be introducing the "Work". Previously we had collections, which many of you used for multi-file projects. A work is similar to a collection in that it will handle multiple files, but it is designed for instances where the files are related to each other as a cohesive unit, for example, software or research data. This will also provide a framework to introduce new features that are specific to a work.

We will also be changing our privacy settings. We will no longer allow content to be private forever. However, you can embargo content, so that it is private for up to two years, after which time it becomes public.

After considerable user testing we will also be improving our interface to make Scholarsphere easier to use. We have especially improved accessibility for visual impairment, color blindness/deficiency, and impaired mobility.

The new version of Scholarsphere will be rolled out on [insert date here] and we will be down for [insert time span here] during which time you will not be able to access content or upload new content. We apologize for any inconvenience that might present, but we think you will like the new features we are adding.
