### ISSUE TITLE
Fedora Object for the User

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#961]
An Object in Fedora that has the following fields:
    Given Name ( exists as First Name)
    Surname (exists as Last Name)
    email (optional)
    ORCID (optional)
    login (optional)

Use Friend of Friend ontology model for our predicates.

child of #764

**Comment by carolyncole** [comment]
We may want to pull in other predicates from Friend of Friend like: department, title.

**Comment by carolyncole** [comment]
Linked open data example from ORCID: http://orcid.org/0000-0003-0837-2362

**Comment by carolyncole** [comment]
We will want to index all fields in solr  for searching

**Comment by carolyncole** [comment]
1. Look at FOF for predicates
1. Create Object Code
1. Create Object Index

**Comment by carolyncole** [comment]
Login is the psu id for the person.  We need a rdf predicate for this.

**Comment by carolyncole** [comment]
Changing from first name, middle name to given name and family name.

**Comment by val99erie** [comment]
We submitted a PR that converts creator to a Person model instead of a String, which fulfills part of this story.
https://github.com/psu-stewardship/scholarsphere/pull/1026/commits

In order to complete this story, these fields still need to be added to the Person model and creator partials:
- [ ] ORCID ID
- [ ] PSU login

We don't need to add the field(s) for the alias list as part of this story.  Alias list should be added as part of stories #991 and #992.

**Comment by awead** [comment]
Put Orcid id in the model but not in the UI. The nested form in the work edit page should include PSU id and email.
