### ISSUE TITLE
Admin editing work overwrites uploaded on behalf of 

### ISSUE THREAD

**Issue by olendorf** [psu-libraries/scholarsphere-3#970]
When I edited a users work that had been created and uploaded on behalf of someone else,  it appears the uploaded on behalf of value was changed to someone on the list of people I can proxy for.  I went back and looked, and it does appear that it picks the top person from my list and makes that person who was proxied for rather than the original value.

**Comment by awead** [comment]
@olendorf @cam156 I think the problem is that the "On behalf of" dropdown menu gets rendered during edit. If you aren't the proxy for the same person as the original uploader was, which it's unlikely that you would be, it's not going to render with that person selected. 

I've checked this locally, and when I try to edit a work that was proxied by someone else, i.e. `on_behalf_of` is "xyz123", `cam156` comes up as the selected "On Behalf of" user because she's the only person in my proxy list. If I was a proxy for "xyz123", then it would be selected. The dropdown doesn't seem to allow for empty selections, it's either "yourself" or one of your proxies. Curiously, "yourself" is not one of the options when I'm editing a proxied work.

I see two solutions:
1.  If the current `on_behalf_of` is not in the user's list of proxies, render the dropdown with an empty selection; or,
2. don't render the dropdown at all for edits.

The first is a nicer because you could change the value if need be, for example of you were a proxy for many people and accidentally selected the wrong one when you created it. For admins, we could render a different input that allows you to enter anyone, using the same process we use for user permissions. This would allow someone like Rob to make corrections to the work, no matter whose proxy was whom.

The admin solution option should be ticketed separately, though.
